# Generated by Django 3.1.7 on 2021-06-15 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_credit', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Info',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('course_max_count', models.IntegerField(default=-1)),
                ('course_class', models.CharField(max_length=10)),
                ('course_credit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.course_credit')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Couse_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('verbose_grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Selected_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(default='', max_length=20)),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lecture.student_class')),
                ('student_dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lecture.department')),
                ('student_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lecture.student_status')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.building')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.room')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_score', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.course_info')),
                ('feedback_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.feedback_result')),
                ('selected_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.selected_result')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
        migrations.AddField(
            model_name='course_info',
            name='course_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.course_status'),
        ),
        migrations.AddField(
            model_name='course_info',
            name='course_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.time'),
        ),
        migrations.AddField(
            model_name='course_info',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.couse_type'),
        ),
        migrations.AddField(
            model_name='course_info',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.department'),
        ),
        migrations.AddField(
            model_name='course_info',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.grade'),
        ),
        migrations.AddField(
            model_name='course_info',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.location'),
        ),
        migrations.AddField(
            model_name='course_info',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.semester'),
        ),
        migrations.AddField(
            model_name='course_info',
            name='student',
            field=models.ManyToManyField(through='lecture.Enroll', to='lecture.Student'),
        ),
        migrations.AddField(
            model_name='course_info',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.teacher'),
        ),
    ]
