# Generated by Django 3.1.7 on 2021-06-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Couse_Type',
            new_name='Course_Type',
        ),
    ]
