# Generated by Django 3.1.7 on 2021-06-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20210615_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_credit',
            name='course_credit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback_result',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
