# Generated by Django 3.1.7 on 2021-06-15 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20210615_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='course_info',
            name='course_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lecture.course_time'),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
